### ISSUE TITLE
Using gitrob for sensitive info that can be reported under the responsible disclosure

### ISSUE THREAD

**Issue by warlock0007** [michenriksen/gitrob#105]
Hello all,

I am new in the field of security and want to learn some good recon tactics. 2 weeks back, got to know about gitrob. Such an amazing tool but need some suggestion on analyzing the results.

I was doing recon for one organization n got on ruby on rails secret token file. This issue is pretty much critical as it can lead to [RCE.](http://robertheaton.com/2013/07/22/how-to-hack-a-rails-app-using-its-secret-token/).

1. how we are going to figure out the URL against which we are going to use this secret token?
2. How can I confirm the false positive and negative. 
3. How to decide if the issue can be reported under responsible discloser

Hoping for the positive suggestions from the community.

**Comment by michenriksen** [comment]
Hey there, Gitrob is not a point-and-pwn tool, you will need to sift through the findings and think about what might be exploitable. In the case of exposed Rails secret tokens, you will likely find a bunch of them on most Orgs that you analyze, however in order to be a valid finding for a Bug Bounty it will of course need to be an application that relates to the company and is within scope of their program. Most of the time, they are just tokens for small test apps and similar that might not even be deployed anywhere.

> how we are going to figure out the URL against which we are going to use this secret token?

Sometimes you can figure out if an application is deployed by simply checking if a URL has been set on the repository. If not, you might find clues to where it is by looking through the code, especially application Views and layouts.

> How can I confirm the false positive and negative.

You can use the PoC exploit code in the [blog post](http://robertheaton.com/2013/07/22/how-to-hack-a-rails-app-using-its-secret-token/) you linked to but change the payload to something like:

```ruby
 erb.instance_variable_set :@src, "sleep 5"
```

If the exploit request takes about 5 seconds to respond, you can be pretty certain that you have code execution. Execute it a couple of times to be sure. Another option would be to trigger an outgoing HTTP request with a payload like:

```ruby
erb.instance_variable_set :@src, "require 'net/http'; Net::HTTP.get('example.com', '/something.html');"
```

You can use a service like http://requestb.in/ to check if you receive a request from the server. Keep in mind that this probe might get blocked by egress firewalling though.

> How to decide if the issue can be reported under responsible discloser

If you find an RCE on a system that is within scope, you should definitely report it. Other than that, look through the findings and think like a bad guy. I personally find people's dotfiles very interesting as you can find a lot potentially sensitive information like command history, credentials, API keys, etc. Even a hostname to a "secret" system that isn't meant to be publicly known can be very valuable as it increases the attack surface of the target and can be probed for vulnerabilities.

Hope that helps you. Have fun and be responsible! ;)

**Comment by warlock0007** [comment]
Thanks a lot. This was a great help. Got your porint :)
