### ISSUE TITLE
Scanning private repositories too

### ISSUE THREAD

**Issue by jmuellerAS24** [michenriksen/gitrob#17]
Nice tool!
But please allow private repositories to be scanned too.
There might be a case where you would want to make a private repository public and check it in advance.
Also I would like to discover for example AWS credentials even if they are in a private repository.

Thanks!

**Comment by jonaf** [comment]
This is already supported. Make sure your github access token has support for listing private repos.

**Comment by michenriksen** [comment]
Hi @jmuellerAS24, thanks for reporting. @jonaf is right that Gitrob will scan private repositories if the access token used has the privileges to see them, however there is a slight problem when you afterwards want to see the file contents in the web interface, since the contents are fetched *on-demand* by requesting the raw content URL of a file, and these endpoints don't support authentication with access tokens at the moment.

As a work-around, you should be able to click on the `View file on GitHub` link in the bottom right corner.
