### ISSUE TITLE
Warn me when files whith a given hash are found

### ISSUE THREAD

**Issue by pfigue** [michenriksen/gitrob#24]
I want to be sure that no private key is leaked into any of our repositories.

I don't want to provide Gitrob the private key itself, but only its (e.g. SHA256) hash and let Gitrob check that no file has that hash.

Maybe, I should provide Gitrob also the file size, to check the hash only if the filesize matches. I want to avoid Gitrob computing hashes for each file if it is not necessary (e.g. a directory full of big JPG files). Relaying in the filename and/or extension may not be accurate.

Maybe, I can provide a list of sensitive hashes (with hashing algorithm? with size?) in the ~/.gitrobrc file.

**Comment by maxlinc** [comment]
I'm not a gitrob maintainer, but wanted to contribute a couple of comments about:
> be sure that no private key is leaked

If you want to make sure that no private key is leaked, then do the hashes matter at all? It seems like a hash would be useful for preventing *specific* keys from being leaked, but not to stop *any* private key from being leaked.

Even if you had a set of hashes for every single private key used by the organization or any member of the organization, it still wouldn't be foolproof because it wouldn't detect:
- Keys that have been converted to a different format (e.g. see [Converting Using OpenSSL](https://www.sslshopper.com/article-most-common-openssl-commands.html))
- Keys that have been insignificantly modified (e.g. apparently leading and trailing whitespace is ignored)
- Keys embedded within other files (e.g. stored in a json "data bag" for use with chef's [certificate cookbook](https://github.com/atomic-penguin/cookbook-certificate/), especially if the data bag is not encrypted)

I think it might be better to search for:
- Filenames associated with private keys (e.g. *.pem)
- Content in configuration files (*.yaml, *.json, *.rb, etc) matching a private key signature (e.g. "-----BEGIN RSA PRIVATE KEY-----")

**Comment by vanhalt** [comment]
+1 to @maxlinc
