### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by laminfaty** [michenriksen/gitrob#30]
I think this tool is very powerful but i have one question. Is there a way to mark a finding as false positive so that Gitrob will not report it next time it runs?

**Comment by vanhalt** [comment]
The answer to your question is no. Gitrob uses a [static pattern file](https://github.com/michenriksen/gitrob/blob/master/patterns.json) to check for sensitive content every time it runs.

Unless we think that we should take this issue as a feature request, we can close it :)

**Comment by laminfaty** [comment]
Do you have any suggestion about adding this feature? I guess I can try to take a stab at it. My approach is eliminate any finding that is not critical.

**Comment by vanhalt** [comment]
I think what you mention is on the path reading this issue: https://github.com/michenriksen/gitrob/issues/26

At this point I can't tell if eliminating findings that are not consider critical can address this. Maybe we should wait for more feedback from @michenriksen

**Comment by laminfaty** [comment]
So I guess we need to wait on @michenriksen to give us feedback.

**Comment by michenriksen** [comment]
Hi @laminfaty, 

Gitrob is currently working in a *stateless* sort of way, which means that it has no knowledge of the findings between each run.

However, I am planning to extend Gitrob so that it is easier to run in a continuous and automated fashion, which would include an ignore/whitelist feature. I don't know when I will get around to implementing this as the first thing is just a general code clean-up and refactoring the data models to make it possible to scan a list of users instead of an organization.

Thanks for jumping in, @vanhalt!
