### ISSUE TITLE
[*] Collecting organization repositories... failed

### ISSUE THREAD

**Issue by michal1elbaz** [michenriksen/gitrob#32]
Hi,
 I'm trying to start gitrob when I get to the configuration wizard it stops when I get the message above and after it:  [!] Gitrob::Github::HttpClient::ClientError: get to /orgs/nfigure/repos?page=1 returned status 404 - options: {:query=>nil}
postgres@kali:/root/gitrob/trunk$ gitrob -h

I can't seem to understand the problem.
Can somebody explain?

**Comment by michenriksen** [comment]
Hi @michal1elbaz,

The reason why you get the error message is because there is no organization on GitHub named [nfigure](https://github.com/nfigure) - However it looks like part of the word co**nfigure**, so it might be a problem with how you envoke the configuration wizard.

What happens if you do `gitrob --configure`?

**Comment by michal1elbaz** [comment]
Thank you for responding
It worked

*Sorry... it's all new to me

**Comment by michenriksen** [comment]
No worries, glad you're up and running. :)
