### ISSUE TITLE
Search private repositories?

### ISSUE THREAD

**Issue by aurcioli-handy** [michenriksen/gitrob#76]
Can gitrob search repositories that are private under an organization? There are valid threat models for secrets committed to private repositories, for example LDAP admin credentials that a service might need to authenticate users.. 

Additionally it can be useful to find instances of bad security patterns where people are committing secrets.

**Comment by HanisHairuddin** [comment]
You can't search Private repositories under an organization, unless if you have the permission to access to that repo, and generate the access key for it.

**Comment by t3h2mas** [comment]
> unless you have the permission to access that repo, and generate the access key for it

That doesn't seam to be the case. I tried just that, and only the public repos of org members were scanned. The key had read access to the private org's repos.

There would be immense value in being able to scan private repositories from a defensive standpoint. Which a commit pipeline would be ideal, some companies need to scan backwards. 

Ideally functionality for me:
 * be able to scan private repositories using the api
 * if that's not possible due to api permissions, be able to point gitrob at a local directory (or directories) and have it process the directories and present findings in the web ui

**Comment by betobrandao** [comment]
@michenriksen, I have the same problem as @kevin-paloit .

My access_token has all the permissions needed for accessing the private repositories of my organization, but GitRob only access the public ones.

To make sure my access token works, I used it in a Python script using the [pygithub](https://github.com/PyGithub/PyGithub) library to access all my organization's repositories data and it works perfectly.

I'd like to know if there is another way to get around this limitation or maybe a specific place for me to look at the source code and change it.

Thanks in advance.
